### ISSUE TITLE
What is accimage?

### ISSUE THREAD

**Issue by hughperkins** [pytorch/accimage#12]
(found it whilst downloading resnet from https://github.com/pytorch/vision , but unclear what it is / why it is?)

**Comment by penguinshin** [comment]
Have you guys noticed that on AWS P3 instances, CPU loading of images is a major bottleneck (by almost 2x) for imagenet JPEGs?

**Comment by hughperkins** [comment]
@penguinshin What if you store the images in h5py files? I haven't tried
this, and presumably it decompresses them, which has its own problems. Just
curious if you have, and what were the results?

**Comment by penguinshin** [comment]
I haven't tried h5py - good idea. @hughperkins do you work with P3 instances/do you have similar training speeds? (For me, it takes about 32 minutes per epoch on a P3.2xLarge)

**Comment by hughperkins** [comment]
@penguinshin I mostly use nlp, rnns, which are only marginally faster on P3s, given my poorly optimized code. So, I mostly spin up 4 times as many g3s instead...

But, eg Justin Johnson seems to be a fan of using h5py for storing preprocessed images, eg https://github.com/jcjohnson/densecap/blob/master/preprocess.py#L385 . I've used it a bit, because it's more convenient than having a folder with a zillion files in it. Performance seems ok-ish, but I've only dabbled in it; and not sure how it compares with just storing the images directly on disk, hence my question :)

**Comment by xvdp** [comment]
I know this is an old topic, but Im crossing it now. Ive been trying to work with lots of small images and a fast loader is desirable.
I looked into h5py and is blazing fast and can give you partial data - if you pack it correctly. One could pre resize the dbs, which I dont like, or binpack it. I did that but h5py is uncompressed so makes huge files( or has very slow compression). 
Then I looked into leveldb. I like that because if anyone is doing something right with lots of data is google. It is slower than h5py but compresses very well and is reasonably fast. There dont seem to be good python wrapper or tools around it, but they shouldnt be hard to write.
I checked speed of accimage, on (open, one operation, and a to tensor) and it is between 4 and 6 times faster than PIL or opencv for the same operations.
Unfortunately accimage breaks some of the transformations (e.g. TenCrop) from torchvision as it operates in place. I forked it and modified it to add a .copy(), but that isnt really a good answer unless one modifies the transformations from torchvision, so maybe Ill modify it to return copy of data instead of reference for all operations.

**Comment by xvdp** [comment]
ok, my fork now has the same default behaviour as PIL, ie. it does not break FiveCrop or any other transformation that requires copy of the image. I keep original accimage original behaviour optional with an in_place kwarg.

https://github.com/xvdp/accimage

**Comment by soumith** [comment]
@xvdp would you be up for sending a PR from your fork to mainline?

**Comment by soumith** [comment]
or even better question, would you want to maintain accimage mainline, rather than your fork?

**Comment by xvdp** [comment]
Hi Soumith, I didnt see this mail ( went to my junk box ). Sure I can
maintain mainline.  Let me know how I go about doing this, rules
permissions, etc.
Ill be looking at accimage again early next week after Im done with a
project im completing.

thanks
